---
title: "MP3"
author: "Mathena Abramson"
date: "November 13, 2017"
output: html_document
---
```{r}
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "imdb")
```

```{r, message = FALSE}
db %>%
  dbGetQuery("SELECT COUNT(DISTINCT t.id) AS count, title, kind_id, link_type_id, production_year, m.info_type_id, m.info
FROM title t
JOIN movie_link ON t.id = linked_movie_id
JOIN movie_info m ON t.id = m.movie_id
WHERE kind_id = 1 AND link_type_id = 1
GROUP BY production_year;") %>%
ggplot(aes(x = production_year, y = count)) +
	geom_line(size = 1) +
  geom_area(fill = "#d3a3fa") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  theme(plot.title = element_text(hjust = 0.5),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank(),
        panel.background=element_blank()) +
  labs(title = "Trend of Movie Sequels Over Time",
       x = "Production Year",
       y = "Number of Sequels",
       caption = "(Data from IMDB)")
  
```


